### ISSUE TITLE
Help needed on nw-collection-003.xml

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#100]
Sorry, I do not get the test: What rule did we agree on?

Why is XD0008 expected on p:with-option as @select does not depend on the context item?

What did I miss?

**Comment by ndw** [comment]
I agree. That looks like it should pass to me. Will review this evening.

**Comment by xml-project** [comment]
Could you please have a look at your test "ab-variable-021b.xml" too . Looking at the current specs I think it should fail with XD0008. The "only if referring to the context-item"-rule is stated currently only for AVT/TVT, not for p:variable and p:with-option. This might be the reason why "nw-collection-003.xml" is expected to fail.

I think that if we have this rule for AVT/TVTs we should have it for p:variable and p:with-option too. Every else would just be to confusing. But reading the specs, its AVT/TVT only, isn't it?

**Comment by xml-project** [comment]
@ndw Any new thoughts on this? I think XD0008 shouldn't be raise on wrap-sequence as the XPath expression does not reply on the context node. To my reading this test should pass and result in
````
<wrapper0>
  <doc>2</doc>
</wrapper0>
````
What did I miss?
