### ISSUE TITLE
Undefined error codes

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#113]
The test-suite page https://xproc.github.io/3.0-test-suite/errors.html (at the end of the Dynamic Errors) marks some errors with "This error code is not defined in any of the specifications."
I checked it and they are all defined into the step library, but are not step errors because they apply to p:load, p:document (and p:inline).

**Comment by ndw** [comment]
Fixed by https://github.com/xproc/3.0-steps/pull/188
