### ISSUE TITLE
Add a notion of platform to the tests

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#132]
Tests for platform X should be skipped on platform Y

**Comment by ndw** [comment]
We don't have any actual use for this at the moment. I'm going to close it. We can reopen it or recreate it when we have a test that only runs on one platform.

**Comment by gimsieke** [comment]
I’m willing to contribute platform-dependent test pipelines for `p:urify()` once I get hold of a 3.0 processor, even if `p:urify()` weren’t implemented yet. But I’m afraid without an actual processor there’s too much that might go wrong syntax-wise just out of sloppiness. 
I think I’d design it as a single pipeline that will invoke or skip `p:urify()` on some arguments, and verify the results, depending on the output of `p:os-info`.

**Comment by ndw** [comment]
Righto. I'll figure something out for platform dependent tests. I'll make "implement p:urify" next on my list.

**Comment by gimsieke** [comment]
In this [Gist](https://gist.github.com/gimsieke/7a9362f47aa8b38dc1b2fc4bced79bf4) there’s an attempt at a test pipeline. It’s using the file path / URI examples from the spec as a starting point. Caution: It was written without an XProc 3.0 processor at my disposal.

**Comment by xml-project** [comment]
> Am 02.01.2020 um 16:52 schrieb Gerrit Imsieke <notifications@github.com>:
> 
> In this Gist there’s an attempt at a test pipeline.

The problem I reported came up, when I try to make a proper test with the test-suite suite schema from this pipeline.

------------------------------------------------
Achim Berndzen
achim.berndzen@xml-project.com

<xml-project /> Achim Berndzen
Kleine Breite 26a
38302 Wolfenbüttel, Germany

http://www.xml-project.com

**Comment by xml-project** [comment]
Notion of platform introduced with pr #449.
