### ISSUE TITLE
Test ab-hash-007.xml

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#191]
Hi Achim,

I don't believe that `ab-hash-007.xml` should pass. After the step runs, `doc/text()` consists of 18 spaces followed by the hash, so `doc/text()='852b1f51'` is not true.

We can fix the test by changing the expression to compare against the normalized space version of the string, or remove the spaces from the input document, or probably any of several other ways.

I'm happy to send along a fix, if you have a preference.

**Comment by xml-project** [comment]
I agree. I will file a fix for this test as soon as I know, why my implementation passes it.

**Comment by xml-project** [comment]
Covered with PR #192

**Comment by xml-project** [comment]
Fixed with #192
