### ISSUE TITLE
Refactor the test suite build process

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#213]
It's perilously close to running out of memory.

**Comment by xml-project** [comment]
Now it is: Java Heap space error. [See](https://travis-ci.org/xml-project/3.0-test-suite/builds/562138721?utm_source=github_status&utm_medium=notification)

**Comment by ndw** [comment]
Yep. That's out-of-memory. Sigh. I'll try to refactor things this evening.

**Comment by ndw** [comment]
I believe this is fixed. Time will tell.
