### ISSUE TITLE
Challenging test err-xd0063-001.xml 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#217]
To my reading this should not be an error, but an empty text document. 
[Prove](http://spec.xproc.org/master/head/xproc/#text-value-templates):

> If the content type is not an XML media type or an HTML media type, each text value template is replaced by the concatenation of the serialization of the nodes that result from evaluating the template.

Did I misunderstood this ruling?

**Comment by ndw** [comment]
[Disprove](http://spec.xproc.org/master/head/xproc/#err.inline.D0063):
>  It is a dynamic error (err:XD0063) if the p:inline contains any XML markup and has a content type that is not an XML media type or an HTML media type. 

Looks like we have a conflict in the spec. I'll open an issue on the specification that proposes removing `err:XD0063`.

**Comment by xml-project** [comment]
Ok, I see your point. To me XD0063 is for this:
````
<p:inline content-type="text/plain"><element /></p:inline>
````
Here we have XML markup, while the TVT rule says, that text is inserted. We should make this more precise, but I think we need to keep XD0063.

**Comment by ndw** [comment]
Ah. Yes. I see where I got it wrong 😄 

I don't know if we need any spec changes or not. But I concur with your analysis.

**Comment by xml-project** [comment]
fixed with pr #218
