### ISSUE TITLE
Problem with test Test err:XS0001 005

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#222]

**Comment by xml-project** [comment]
Test is:
````
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="3.0">
    <p:viewport name="step" match="doc">
      <p:with-input>
        <p:pipe step="step" port="result"/>
      </p:with-input>
      <p:identity/>
    </p:viewport>
 </p:declare-step>
````
I see what this test should do, but "step" does not have an output port "result". To my reading it has an anonymous output port.
What did I miss?

**Comment by ndw** [comment]
I think that's a bug in the test. The output port 'result' needs to be declared on the viewport. I wonder why I pass that test? I'll have to check later; my implementation is in pieces on the floor again as I sort out a troublesome aspect of the environment.

**Comment by ndw** [comment]
Feel free to fix it, or assign it to me and I'll fix it later today.
