### ISSUE TITLE
Question about ab-delete-020.xml

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#236]
Why is the content type expected to be text/plain?

Why is the serialization key not expected to be in the map?

I get:

```
<c:document-properties xmlns:c="http://www.w3.org/ns/xproc-step" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <base-uri>http://base</base-uri>
  <content-type>application/xml</content-type>
  <serialization map="true"/>
  <bonus-prop>prop</bonus-prop>
</c:document-properties>
```

which looks like a correct result to me.

**Comment by xml-project** [comment]
Sorry, but I tend to disagree: As the `p:delete` deletes the `element` element from the source document, the result is a single text node, wrapped in a document node. Therefor the result is a text document with content-type `text/plain` and no document property is preserved.
What did I miss?

**Comment by ndw** [comment]
Fair catch. It's possible I'm not handling that correctly in `p:delete`.
