### ISSUE TITLE
Doubts on result of changed test

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#238]
I would like to doubt, that the tests changed with pr #235 are correct: The select expression in the TVT;
````
<result>{/ERROR/text()}</result>
````
has to be empty, The root element of the document appearing as context item is `c:errors`, so the correct expression is `/c:errors/c:error/ERROR/text()`.
This is for both tests.

Sorry for approving the PR without testing. Will send a PR soon.

**Comment by ndw** [comment]
Yes, you're right. Total oversight on my part.
