### ISSUE TITLE
Shouldn't ab-uuid-008 pass?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#243]
I thought we decided replacing the root was ok and the result was a single text node. Am I mistaken?

**Comment by xml-project** [comment]
I think this is related to this [issue](https://github.com/xproc/3.0-steps/issues/130).
As we have no decision on it yet, the test reflects the current state of the specs to my reading.
Should we mark issue 130 as "consensus reached"?

**Comment by ndw** [comment]
Yes, that's the issue I was thinking off. I think we have consensus.

**Comment by xml-project** [comment]
OK. The test is 15h behind the consensus. I will update the specs and change the test.

**Comment by xml-project** [comment]
Fixed with pr #248
