### ISSUE TITLE
Fix ab-validate-with-XML-Schema-007

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#262]
This test is a namespace validation with a reference to a file on the old XProc 1.0 Test suite page. We should fix this some das.

**Comment by xml-project** [comment]
@ndw Thanks. As I see it, I know what I should have done. I tried it via the GitHub repo and failed.

**Comment by ndw** [comment]
No worries. That one’s a little tricky because I believe there are tests that expect to find the schematic at the namespace URI.
