### ISSUE TITLE
Assertion text in https://github.com/xproc/3.0-test-suite/blob/master/test-suite/tests/ab-xslt-042.xml seems wrong

### ISSUE THREAD

**Issue by martin-honnen** [xproc/3.0-test-suite#309]
https://github.com/xproc/3.0-test-suite/blob/master/test-suite/tests/ab-xslt-042.xml tests `<s:assert test="/wrapper/result[2]/text()='http://xproc-test/xslt/two.xml'">Element 'result[2]' does not have a text child 'http://xproc-test/two/one.xml'.</s:assert>`, I think it is meant to say `<s:assert test="/wrapper/result[2]/text()='http://xproc-test/xslt/two.xml'">Element 'result[2]' does not have a text child 'http://xproc-test/xslt/one.xml'.</s:assert>`.

**Comment by xml-project** [comment]
@martin-honnen Yes, the text is obviously wrong. It should read:
`Element 'result[2]' does not have a text child 'http://xproc-test/xslt/two.xml'.`
Thanks for finding this. Will fix it tomorrow.

**Comment by xml-project** [comment]
Fixed with #310
