### ISSUE TITLE
Cannot publish tests with invalid xml:base attributes

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#322]
@xml-project reported this in email a few days ago. Just putting it here for tracking.

I've identified the problem and decided that the "simplest" solution is a new XML Calabash option that will tell the processor to ignore invalid XML base values. XML Calabash 1.1.30 and the Gradle extension library 1.3.6 should be ready by tomorrow. I hope.

**Comment by xml-project** [comment]
@ndw Works great, thank you very much.
