### ISSUE TITLE
Is test "ab-option-020.xml" right?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#34]
@ndw Could you please have a quick look at [ab-option-020.xml](https://github.com/xproc/3.0-test-suite/blob/master/test-suite/tests/ab-option-020.xml)?

I think this test is wrong and should fail with XD0036, because "'false'" can not be casted to xs:boolean. Right?

**Comment by ndw** [comment]
This seems to work:
```xml
  <xsl:value-of select="'false' cast as xs:boolean"/>
```

**Comment by xml-project** [comment]
'false' works, but it is select="'false'" (double quotes!)

**Comment by ndw** [comment]
I think that's equivalent to my XSLT test. select="'false'" makes the value the string false. The quotes don't turn up in the value; if you take out the inner quotes, you get an XPath expression that's attempting to select a `<false>` element from the current context.

**Comment by xml-project** [comment]
@ndw Yes, you are right - mistake on my side.
Thanks!
