### ISSUE TITLE
Proposed error code changes

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#343]
If `ab-p-archive-056` is supposed to return `err:XC0085`, then I assert that `ab-p-archive-057` must also.

**Comment by xml-project** [comment]
Sorry, but I disagree with your conclusion. In 056 there is no format given and the processor does not know how to handle the "archive"-document -> XC0085.
In 057 there is a format given ("zip") and the processor know, that the "archive"-document is not a ZIP -> XC0081.

I think that the rationale behind 0081 and 0085, but may be I am wrong with that.

**Comment by ndw** [comment]
But the default for `format` is "zip". If you don't specify a format, you get `zip`.

**Comment by ndw** [comment]
I believe this is subsumed by #352 as well.
