### ISSUE TITLE
Text-sort lines

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#346]
The test suite results for the text-sort steps appear to be using newlines as separators:

```
<s:assert test="wrapper/text()='A&#xA;B&#xA;C&#xA;D'">Text is not sorted correctly.</s:assert>
```

I think each line, including the last line, should end with a newline. Why is separator better?

**Comment by xml-project** [comment]
@ndw Sorry, I do not get your point. Would you mind to reformulare the problem?

**Comment by ndw** [comment]
After sorting "C D B A" (for example), the test suite results expect
```
A&#10;B&#10;C&#10;D
```
That's using the newline as a separator. I think that each line should end with a newline:
```
A&#10;B&#10;C&#10;D&#10;
```
This could come down to just being a matter of opinion, but I wonder if you have a specific reason for the choice of separator.

**Comment by xml-project** [comment]
OK, now I see your point. We have different interpretation of

> Lines are identified as described in XML, 2.11 End-of-Line Handling.

I understand "B&#10;A" as two lines (and so the sorted result should have two lines too). "B&#10;A&#10;" accordingly has three lines (the last one is empty). And the sort result is
"&#10;A&#10;B"

Did I get your point right? Do you think this is is a matter of opinion? I think we should fix this in the specs.

**Comment by ndw** [comment]
I agree we should fix it in the specs. I expect you're right, but it wasn't consistent with my experience. I'll do some more testing.

**Comment by xml-project** [comment]
I think we can close this.
