### ISSUE TITLE
What is ab-contenttypes-003.xml testing?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#38]
Test `ab-contenttypes-003.xml` claims that it raises `err:XD0038` but I don't see why it should.

* There's no restriction on the `content-type` of `p:input`
* The `content-type` `text/plain` is perfectly fine
* There's no restriction on the `content-types` of the source input port of `p:identity`

What (obvious thing) am I missing?

**Comment by xml-project** [comment]
Additionally:
Some error for missing @content-types on p:output on
ab-contenttypes-006.xml

**Comment by xml-project** [comment]
> So yes, I'm sure you meant "\*/*", in fact that's probably what you typed!
Yes, sorry. Make this mistake over and over gain.

**Comment by xml-project** [comment]
fixed with pr #43
