### ISSUE TITLE
I don't think ab-http-request-061 should fail

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#404]
This test is checking that it should be an error if two header are specified and they differ only in case. However, the spec says:

> All of the document properties will be used as headers except “base-uri”, “serialization” and any property with a name that already appears in the headers map. (In other words, if the same header name appears in both places, the value from the map is used and the value from the document properties is ignored.) 

I think it follows that if "header" exists in the map, a property named "HEADER" is not added to the map, but that it isn't an error.

**Comment by xml-project** [comment]
Right. Please consider all my tests for p:http-request to be preliminary. Most of them were written before the big last on this step. For some I try to adapt them to the new specs, but I am pretty sure I did not hit all.

**Comment by ndw** [comment]
I fixed this a couple of days ago.
