### ISSUE TITLE
Test for p:validate-with-schematron rest on implementation specific behaviour

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#436]
Test [ab-validate-with-schematron-008](https://test-suite.xproc.org/tests/ab-validate-with-schematron-008.html) (Ported from the 1.0 test suite) tests an invalid document with a non existing phase. It expects to pass. But this behaviour seems to be implementation specific with the skeleton implementation.

To my reading ISO/IEC 19757-3 does not specify the correct behaviour in this case. I found at least one Schematron implementation to raise an error if used phase is not defined.

Proposal: Remove the test!

**Comment by dmj** [comment]
I would argue the raising an error is the right thing to do. The Skeleton implementation in fact does this: It reports an error but does not stop the stylesheet compiler.

From my understanding raising an error is implied by the spec. It mandates, that any phase that should run by default must be defined. I.e. the datatype of the @defaultPhase attribute is xs:IDREF.

**Comment by dmj** [comment]
Please also see https://github.com/Schematron/schematron/issues/87

**Comment by xml-project** [comment]
Given the comments of @dmj and Tony Graham, I think we have to remove the test.
Fixed with #437
