### ISSUE TITLE
More documentation on newly introduced meta vocabulary needed

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#54]
I think "date" is pretty easy to understand, "author" is a question of personal convention or discipline (name, given-name or "given-name name").

What about `specref`?

**Comment by ndw** [comment]
I was vague on purpose. We could try to tighten it up. Until we decide to get rigorous about tying tests back to the spec, I thought it would be good to have somewhere to put a link or even just notes.

**Comment by xml-project** [comment]
Ok, so I close this one. Go a head with some examples of links, I will try to follow as good as I can.
