### ISSUE TITLE
errorcode on doc-prop-005

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#58]
Currently test "doc-prop-005" is expected to fail with xqterr:XPTY0004 (which is an XPath error). But this is not the point. 

To my reading this pipeline will never compile, because the primary input port of step "identity" is not bound. So XS0032 ("It is a static error if no connection is provided and the default readable port is undefined.") would be right, but miss the point of the test.

What did I miss?

**Comment by ndw** [comment]
Are we looking at the same test?
```xml
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
                xmlns:cx="http://xmlcalabash.com/ns/extensions"
                name="main"
                version="3.0">
  <p:output port="result"/>

  <p:variable name="a" select="3 + 4"/>

  <!-- this should fail, $a isn't a document -->
  <p:identity>
    <p:with-input port="source" select="p:document-properties-document($a)/p:document-properties/a"/>
  </p:identity>

</p:declare-step>
```

**Comment by xml-project** [comment]
Yes. I think there should be a binding for primary port 'source' on p:identity. 

At least my implementation says so, and it looks right to me: Unbound primary input port.

What did I miss?

**Comment by ndw** [comment]
I'm confused. how is the `p:with-input port="source"` not a binding for the primary input on `p:identity`?

**Comment by ndw** [comment]
Oh! Nevermind. I see. Yes, that looks broken. I propose that we add a `p:empty`.

**Comment by xml-project** [comment]
👍
