### ISSUE TITLE
Running tests locally

### ISSUE THREAD

**Issue by JDziurlaj** [xproc/3.0-test-suite#647]
I am looking at extending this test-suite concept for a project that involves XProc. However, I am having difficulty running the test suite locally. The `README.md` mentions targets like `validate_all_tests` but I don't such defined in the build.gradle in this repo. Am I missing something?

**Comment by ndw** [comment]
Looks like maybe the README has got a little out of date. I'll see about fixing that. In the meantime, if you just run `./gradlew` what errors do you get?

**Comment by JDziurlaj** [comment]
I no longer get errors (I had to update the `build.gradle` to handle a Perl script on Windows, I'll file a PR), I get output in the `build/` folder, but it is unclear if its actually running the tests against the processors (e.g. I didn't specify calabash or morgana and I don't see their binaries anywhere).

**Comment by ndw** [comment]
Ah. Sorry. Right. I see the confusion. The test suite build doesn't actually run the tests. The implementations have their own test drivers, probably quite different, and submit reports of results. The test-suite repository tests that the tests are correct and publishes the results.

Depending on which implementation you're planning to extend, you'll need to wrestle with the individual test drivers.

**Comment by JDziurlaj** [comment]
I opened an issue with the Morgana maintainer.
