### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#68]
All tests with an additional namespace declaration on the outer p:declare-step are broken somehow by the conversion because the namespace is now moved to the element, where it is needed.
As a consequence it is no longer available on p:declare-step/type. E.g. ab-connection-008.xml.

Since these are only a few test (ca. 30) I will fix them by hand.

**Comment by ndw** [comment]
Awww, dang it. I tried to make sure the namespaces went in the right places. Sorry I missed those. And sorry about the confusion on revision history. I guess I changed my mind (so that `t:info/t:revision[1]` is always the newest) and didn't update the docs.

**Comment by xml-project** [comment]
Fixed with pr #79
