### ISSUE TITLE
Shouldn't ab-step-available-061 raise err:XS0115?

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#759]
The crux of the test is:

```
         <p:import href="../pipelines/ab-library-007.xpl" use-when="p:step-available('ex:step1')"/>
```

Where `ex:step1` is declared in `ab-library-007.xpl`. That looks like a circular dependency to me:

1. Is that `p:import` in the pipeline? Only if `ex:step1` is declared.
2. Is `ex:step1` declared? Only if the `p:import` is in the pipeline.

Or am I missing something?

**Comment by ndw** [comment]
Unless I'm misreading something, `ab-step-available-064` seems like the same test.

**Comment by xml-project** [comment]
@ndw I think we solved this, didn't we?

**Comment by ndw** [comment]
Yes, I think so.
