### ISSUE TITLE
Wrong error code for ab-function-library-importable-004

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#765]
@ndw Please have a look at the test. The error XD0036 is expected:

> It is a dynamic error if the supplied or defaulted value of a variable or option cannot be converted to the required type.

But the error is with a function parameter inside a TVT. So, I would say, this code is wrong. It should be XD0050.
But both of our implementations pass it.

Change error code?

**Comment by ndw** [comment]
I have a special check for errors that arise in a value template caused by not being able to convert the value to the required type. I expect that check exists only so that I can throw XD0036. I'd be just as happy to throw XD0050.

**Comment by xml-project** [comment]
Yes, same here, but got baffled by XD0036 explicitly refering to options/variables. Changing to XD0050 makes more sense to me.
I will file a PR for this.

**Comment by ndw** [comment]
Consider it approved and just merge it when it's ready :-)
