### ISSUE TITLE
Parameter of p:lookup-uri

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-test-suite#777]
In test "nw-lookup-uri-001.xml" the function p:lookup-uri() is called with a string parameter, but the specification says it has to be xs:anyURI.
To my understanding, either the test or the specification has to be changed.

**Comment by ndw** [comment]
Fair. I think promotion between `xs:anyURI` and `xs:string` is a 4.0 thing...

**Comment by xml-project** [comment]
Fix with #778 Thanks @ndw
