### ISSUE TITLE
More namespace issues

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-test-suite#83]
I'm going to keep this one open for a bit in case I find more, but

* `ab-with-input-select-008.xml` is broken because the default namespace is wrong in the pipeline

**Comment by xml-project** [comment]
Since the revision "http://www.w3.org/1999/xhtml" is the default namespace and I haven't recovered from this yet.
I think we should change this either by removing the `xmlns="http://www.w3.org/1999/xhtml"` declaration from t:test and adding it to the XHTML-fragments in `t:description`.

**Comment by ndw** [comment]
I've fixed it locally by adding xmlns="" to the p:pipeline
Or are you suggesting we should do a wholesale conversion and move the HTML namespaces to the `t:description` elements?

**Comment by xml-project** [comment]
> Or are you suggesting we should do a wholesale conversion and move the HTML namespaces to the t:description elements?

I think this is the better solution. The two of us might remember the problem, but if we invite other people to write tests (and I strongly do!), this may be a trap.

**Comment by ndw** [comment]
Ok. I'll make a pass over all the files. I'll make that change and see about finding any other errors.

**Comment by xml-project** [comment]
Great. There are six more test in a RP. Should I fix them by hand or should we merge them first?

**Comment by ndw** [comment]
Merge 'em in and I'll do the namespace fix up next (instead of trying to track down my try/catch/finally bug 😄 )

**Comment by xml-project** [comment]
Sorry!
